name: paypal_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
